language: csharp
solution: Multiformats.Address.sln
branches:
  only:
   - master
install:
  - nuget restore Multiformats.Address.sln -PackagesDirectory ./packages
script:
  - xbuild /p:Configuration=Release Multiformats.Address.sln
  - mono ./packages/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Multiformats.Address.Tests/bin/Release/Multiformats.Address.Tests.dll
cache:
  - directories:
    - ./packages